import numpy as np
# Copyright © 2005-2019, NumPy Developers.

import pandas as pd
# Copyright (c) 2008-2012, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team

def remove_unused_columns(data_loaded,list_of_accounting_columns_to_include):
    # This is for using less computer memory (RAM)
    list_of_all_accounting_columns          = get_list_of_all_accounting_columns()
    
    list_of_accounting_columns_to_remove = [i for i in list_of_all_accounting_columns if i not in list_of_accounting_columns_to_include]

    # Removing columns from data
    data_loaded.drop(list_of_accounting_columns_to_remove, axis=1, inplace=True)

    return data_loaded

def get_list_of_all_accounting_columns():
    list_of_all_accounting_columns = [
        'Forskning og utvikling',
        'Konsesjoner, patenter, lisenser, varemerker og lignende rettigheter',
        'Utsatt skattefordel',
        'Goodwill',
        'Tomter, bygninger og annen fast eiendom',
        'Maskiner og anlegg',
        'Skip, rigger, fly og lignende',
        'Driftsloesoere, inventar, verktoey, kontormaskiner og lignende',
        'Sum varige driftsmidler',
        'Laan til foretak i samme konsern',
        'Investeringer i tilknyttet selskap',
        'Laan til tilknyttet selskap og felles kontrollert virksomhet',
        'Investeringer i aksjer og andeler',
        'Obligasjoner og andre langsiktige fordringer',
        'Sum finansielle anleggsmidler',
        'Sum anleggsmidler',
        'Varer',
        'Kundefordringer',
        'Andre kortsiktige fordringer',
        'Krav paa innbetaling av selskapskapital',
        'Sum fordringer',
        'Markedsbaserte aksjer',
        'Markedsbaserte obligasjoner',
        'Andre markedsbaserte finansielle instrumenter',
        'Sum investeringer',
        'Kasse/Bank/Post',
        'Sum omloepsmidler',
        'Sum eiendeler',
        'Selskapskapital',
        'Overkursfond',
        'Annen innskutt egenkapital',
        'Sum innskutt egenkapital',
        'Fond for vurderingsforskjeller',
        'Annen egenkapital',
        'Udekket tap',
        'Sum opptjent egenkapital',
        'Sum egenkapital',
        'Pensjonsforpliktelser',
        'Utsatt skatt',
        'Andre avsetninger for forpliktelser',
        'Konvertible laan',
        'Obligasjonslaan',
        'Gjeld til kredittinstitusjoner',
        'Oevrig langsiktig gjeld',
        'Sum langsiktig gjeld',
        'Sertifikatlaan',
        'Leverandoergjeld',
        'Betalbar skatt',
        'Utbytte',
        'Annen kortsiktig gjeld',
        'Sum kortsiktig gjeld',
        'Sum egenkapital og gjeld',
        'Salgsinntekter',
        'Annen driftsinntekt',
        'Inntekt paa investering i datterselskap',
        'Sum driftsinntekter',
        'Endring i beholdning av varer under tilvirkning og ferdig tilvirkede varer',
        'Varekostnad',
        'Loennskostnader',
        'Avskrivning paa varige driftsmidler og immaterielle eiendeler',
        'Nedskrivning av varige driftsmidler og immaterielle eiendeler',
        'Annen driftskostnad',
        'Andre driftskostnader (fou kostnader, adm.kostnader, markedsfoeringskostnader)',
        'Sum driftskostnader',
        'Driftsresultat',
        'Konsernbidrag',
        'Inntekt paa investering i annet foretak i samme konsern',
        'Inntekt paa investering i tilknyttet selskap',
        'Annen renteinntekt',
        'Annen finansinntekt',
        'Sum finansinntekter',
        'Nedskrivning av andre finansielle omloepsmidler',
        'Nedskrivning av finansielle anleggsmidler',
        'Annen rentekostnad',
        'Annen finanskostnad',
        'Sum finanskostnader',
        'Netto finans',
        'Ordinaert resultat foer skattekostnad',
        'Skattekostnad paa ordinaert resultat',
        'Ordinaert resultat',
        'Skattekostnad paa ekstraordinaert resultat',
        'Aarsresultat',
        'Avsatt utbytte',
        'Overfoeringer til/fra annen egenkapital',
        'Sum overfoeringer og disponeringer',
        'Sum immaterielle eiendeler',
        'Investering i datterselskap',
        'Investering i annet foretak i samme konsern',
        'Obligasjoner og andre fordringer',
        'Andre fordringer',
        'Konsernfordringer',
        'Aksjer og andeler i foretak i samme konsern',
        'Andre finansielle instrumenter',
        'Bankinnskudd, kontanter og lignende',
        'SUM EIENDELER',
        'Beholdning av egne aksjer',
        'Annen Egenkapital',
        'Minoritetsinteresser',
        'Sum avsetninger for forpliktelser',
        'Langsiktig konserngjeld',
        'Ansvarlig laanekapital',
        'Skyldige offentlige avgifter',
        'Kortsiktig konserngjeld',
        'SUM GJELD OG EGENKAPITAL',
        'Garantistillelser',
        'Pantstillelser',
        'Salgsinntekt',
        'Sum inntekter',
        'Endring i beholdning av egentilvirkede anleggsmidler',
        'Loennskostnad',
        'Sum kostnader',
        'Renteinntekt fra foretak i samme konsern',
        'Verdiendring av markedsbaserte finansielle omloepsmidler',
        'Rentekostnad til foretak i samme konsern',
        'Ordinaert resultat etter skattekostnad',
        'Ekstraordinaer inntekt',
        'Ekstraordinaer kostnad',
        'Overfoering til/fra fond for vurderingsforskjeller',
        'Fondsemisjon',
        'Andre immaterielle eiendeler',
        'Sum gjeld',
        'Resultat av ekstraordinaere poster',
        'Aarsresultat foer minoritetsinteresser',
        'Investeringseiendom',
        'Biologiske eiendeler',
        'Sum varer',
        'Fond for urealiserte gevinster',
        'Sum annen langsiktig gjeld',
        'SUM EGENKAPITAL OG GJELD',
        'Verdioekning av markedsbaserte finansielle omloepsmidler',
        'Verdioekning andre finansielle instrumenter vurdert til virkelig verdi',
        'Verdireduksjon av markedsbaserte finansielle omloepsmidler',
        'Verdireduksjon andre finansielle instrumenter vurdert til virkelig verdi',
        'Overfoering til/fra fond for urealiserte gevinster',
        'Obligasjoner',
        'Fond',
        'Overfoering til/fra fond',
        'Sum bankinnskudd, kontanter og lignende',
        'Inntekt paa investering i datterselskap og tilknyttet selskap',
        'Inntekt paa andre investeringer',
        'Nedskrivning av finansielle eiendeler',
        'Ekstraordinaere poster',
        'Konserfordringer',
        'Aarsresultat etter minoritetsinteresser',
        'Overkurs',
        'Andre resultatkomponenter for IFRS-foretak',
        'Totalresultat',
        'Avgitt konsernbidrag',
        'Sum resultatkomponenter for IFRS-foretak',
        'Ordinaert utbytte',
        'Tilleggsutbytte',
        'Ekstraordinaert utbytte',
        'Ikke registrert kapitalforhoeyelse',
        'Skattekostnad paa ekstraordinaere poster',
        ]
    return list_of_all_accounting_columns


